# Net
net: 'models.qdgnn.Model'
resume: ''
padding_input: False
device_ids: [3]
in_channels: 4
rinv: True

# Data
dataset: 'fpha'
ntu: '../NTU-RGB-D/qrel/xview'
fpha: '../fpha/quaternion'
use_edge: True
edge_only: False
data_augmentation: True
data_param:
  num_frames: 100

# Optimizer
num_epochs: 100
start_epoch: 1
batch_size: 32
learning_rate: 5e-4
weight_decay: 1e-5

# Log
logdir: 'logs/single_arcos/qdgnn_Rinv'
tqdm: True